// Code generated by azure-service-operator-codegen. DO NOT EDIT.
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.
package customizations

import (
	v20180801 "github.com/Azure/azure-service-operator/v2/api/network/v1beta20180801"
	v20180801s "github.com/Azure/azure-service-operator/v2/api/network/v1beta20180801storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
)

type TrafficmanagerprofileExtension struct {
}

// GetExtendedResources Returns the KubernetesResource slice for Resource versions
func (extension *TrafficmanagerprofileExtension) GetExtendedResources() []genruntime.KubernetesResource {
	return []genruntime.KubernetesResource{
		&v20180801.Trafficmanagerprofile{},
		&v20180801s.Trafficmanagerprofile{}}
}
